git:
  depth: 1
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '4'
  - '5.1'
  - '5'
before_install:
  - npm install -g jspm
  - jspm install
notifications:
  email: false